### ISSUE TITLE
Add language support to Helix text editor

### ISSUE THREAD

**Issue by 0xEquinox** [koto-lang/koto#200]
I love the language, but my main editor is helix, and id rather not open/install vscode just for this language. I don't know how hard it is to add support for it if that's even possible, but I figure I might as well put it here.

**Comment by irh** [comment]
Hi @0xEquinox 👋 

It looks like support for Helix would come from supporting [Tree-sitter](https://tree-sitter.github.io/tree-sitter/creating-parsers). Tree-sitter support should be possible, although I haven't looked into it yet.

**Comment by irh** [comment]
@0xEquinox I finally got around to working on a [tree-sitter parser](https://github.com/koto-lang/tree-sitter-koto), which works with neovim and helix. 

You need to manually define highlight queries but you can use the [default queries](https://github.com/koto-lang/tree-sitter-koto/blob/main/queries/highlights.scm) as a starting point.

Here's what I've added to my `languages.toml`.
```toml
[[language]]
name = "koto"
scope = "source.koto"
injection-regex = "koto"
file-types = ["koto"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
roots = []

[[grammar]]
name = "koto"
source = { git = "https://github.com/koto-lang/tree-sitter-koto", rev = "main" }
```
